### PR TITLE
Create new contact UI

### LINKED ISSUE #12: Create New Contact UI

### PR DESCRIPTION
**Pull request by chiragbagde**

### CODE REVIEW

**Comment by yedhink** [comment]
@chiragbagde https://www.loom.com/share/21233a2a813a463c81032c967a39ba29

**Comment by chiragbagde** [comment]
I have added the explanation in this video.
https://www.loom.com/share/ac4699b039be435da2fdd72815bdaaa5

**Comment by chiragbagde** [comment]
While making an issue in my repository I accidentally made it on Big Binary Wheel. Sorry for this mistake. I tried deleting the issue I couldn't delete it so I closed it.

**Comment by chiragbagde** [comment]
Shall I proceed further with Heroku as I've done the changes?

**Comment by yedhink** [comment]
@chiragbagde Yes. You don't have to wait for my approval to merge PRs or continue with next tasks.

**Pull request merged**
